### ISSUE TITLE
data qc python module not running in test scenario

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/srpAnalytics#32]
If i try to add in additional files the database build is failing. @kimdn can you please take a look?

to repro the problem, run this:
```
sh build_db.sh
```

**Comment by kimdn** [comment]
ok, I will take a look

**Comment by kimdn** [comment]
I see
```
f2=to_be_processed/7_PAH_zf_morphology_data_2020NOV11_tall.csv
f1=to_be_processed/7_PAH_zf_morphology_data_2021_Jan11.csv#
run="/usr/local/bin/docker run -v "$PWD":/tmp srp-analytics "$f2","$f1
```
in build_db.sh

But
```
diff 7_PAH_zf_morphology_data_2021_Jan11.csv
7_PAH_zf_morphology_data_2020NOV11_tall.csv
```
didn't show anything.


So let's remove
f1=to_be_processed/7_PAH_zf_morphology_data_2021_Jan11.csv#

So run will be
`run="/usr/local/bin/docker run -v "$PWD":/tmp srp-analytics "$f2""`

**Comment by sgosline** [comment]
@addymmoran I think i fixed it - some commands were not running in the setup.sh so i put them back in the Dockerfile. can you try now?
