### ISSUE TITLE
buildv1database.R is not found

### ISSUE THREAD

**Issue by kimdn** [PNNL-CompBio/srpAnalytics#48]
When I ran
`source run_tests.sh`

it says
`Fatal error: cannot open file '/srpAnalytics/buildv1database.R': No such file or directory`

<img width="875" alt="Screen Shot 2021-08-19 at 1 46 05 AM" src="https://user-images.githubusercontent.com/3903446/130045461-e50fd8e5-b91b-497d-b97c-2adbcd3143f3.png">

I think that Sara made
buildv1database.R
?

**Comment by sgosline** [comment]
it was moved to a directory incorrect, fixed in #54
